### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by bautrukevich** [spiral/composer-publish-plugin#3]
Can you describe in README, please, how to use your plugin? I think, it would be helpful. Is it actual only for SpiralScout Projects or not?

Thank you.

**Comment by wolfy-j** [comment]
Hi,

this repository drives the plugin system for public resources. We are not sure we are in full favor of this system so no docs presented.

The plugin downloads ZIP releases from a given repository and publishes them into the designated locations. This is an example:
https://github.com/spiral/toolkit/blob/master/composer.json#L22

**Comment by bautrukevich** [comment]
Thank you!
